/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.ecommerce.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.rivetlogic.ecommerce.service.persistence.NotificationPK;

import java.io.Serializable;

/**
 * The base model interface for the Notification service. Represents a row in the &quot;rivetlogic_ecommerce_Notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.ecommerce.model.impl.NotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.ecommerce.model.impl.NotificationImpl}.
 * </p>
 *
 * @author isaiulate
 * @see Notification
 * @see com.rivetlogic.ecommerce.model.impl.NotificationImpl
 * @see com.rivetlogic.ecommerce.model.impl.NotificationModelImpl
 * @generated
 */
public interface NotificationModel extends BaseModel<Notification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification model instance should use the {@link Notification} interface instead.
	 */

	/**
	 * Returns the primary key of this notification.
	 *
	 * @return the primary key of this notification
	 */
	public NotificationPK getPrimaryKey();

	/**
	 * Sets the primary key of this notification.
	 *
	 * @param primaryKey the primary key of this notification
	 */
	public void setPrimaryKey(NotificationPK primaryKey);

	/**
	 * Returns the order ID of this notification.
	 *
	 * @return the order ID of this notification
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this notification.
	 *
	 * @param orderId the order ID of this notification
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the subject of this notification.
	 *
	 * @return the subject of this notification
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this notification.
	 *
	 * @param subject the subject of this notification
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this notification.
	 *
	 * @return the body of this notification
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this notification.
	 *
	 * @param body the body of this notification
	 */
	public void setBody(String body);

	/**
	 * Returns the sender of this notification.
	 *
	 * @return the sender of this notification
	 */
	@AutoEscape
	public String getSender();

	/**
	 * Sets the sender of this notification.
	 *
	 * @param sender the sender of this notification
	 */
	public void setSender(String sender);

	/**
	 * Returns the recipients of this notification.
	 *
	 * @return the recipients of this notification
	 */
	@AutoEscape
	public String getRecipients();

	/**
	 * Sets the recipients of this notification.
	 *
	 * @param recipients the recipients of this notification
	 */
	public void setRecipients(String recipients);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rivetlogic.ecommerce.model.Notification notification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rivetlogic.ecommerce.model.Notification> toCacheModel();

	@Override
	public com.rivetlogic.ecommerce.model.Notification toEscapedModel();

	@Override
	public com.rivetlogic.ecommerce.model.Notification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}