/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.ecommerce.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ShoppingOrderItem service. Represents a row in the &quot;rivetlogic_ecommerce_ShoppingOrderItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemImpl}.
 * </p>
 *
 * @author isaiulate
 * @see ShoppingOrderItem
 * @see com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemImpl
 * @see com.rivetlogic.ecommerce.model.impl.ShoppingOrderItemModelImpl
 * @generated
 */
public interface ShoppingOrderItemModel extends BaseModel<ShoppingOrderItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Shopping Order Item model instance should use the {@link ShoppingOrderItem} interface instead.
	 */

	/**
	 * Returns the primary key of this Shopping Order Item.
	 *
	 * @return the primary key of this Shopping Order Item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Shopping Order Item.
	 *
	 * @param primaryKey the primary key of this Shopping Order Item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the item ID of this Shopping Order Item.
	 *
	 * @return the item ID of this Shopping Order Item
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this Shopping Order Item.
	 *
	 * @param itemId the item ID of this Shopping Order Item
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the create date of this Shopping Order Item.
	 *
	 * @return the create date of this Shopping Order Item
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this Shopping Order Item.
	 *
	 * @param createDate the create date of this Shopping Order Item
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this Shopping Order Item.
	 *
	 * @return the modified date of this Shopping Order Item
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this Shopping Order Item.
	 *
	 * @param modifiedDate the modified date of this Shopping Order Item
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the product ID of this Shopping Order Item.
	 *
	 * @return the product ID of this Shopping Order Item
	 */
	@AutoEscape
	public String getProductId();

	/**
	 * Sets the product ID of this Shopping Order Item.
	 *
	 * @param productId the product ID of this Shopping Order Item
	 */
	public void setProductId(String productId);

	/**
	 * Returns the order ID of this Shopping Order Item.
	 *
	 * @return the order ID of this Shopping Order Item
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this Shopping Order Item.
	 *
	 * @param orderId the order ID of this Shopping Order Item
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the quantity of this Shopping Order Item.
	 *
	 * @return the quantity of this Shopping Order Item
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this Shopping Order Item.
	 *
	 * @param quantity the quantity of this Shopping Order Item
	 */
	public void setQuantity(int quantity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rivetlogic.ecommerce.model.ShoppingOrderItem shoppingOrderItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rivetlogic.ecommerce.model.ShoppingOrderItem> toCacheModel();

	@Override
	public com.rivetlogic.ecommerce.model.ShoppingOrderItem toEscapedModel();

	@Override
	public com.rivetlogic.ecommerce.model.ShoppingOrderItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}