/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.ecommerce.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rivetlogic.ecommerce.model.ShoppingOrder;
import com.rivetlogic.ecommerce.service.ShoppingOrderLocalServiceUtil;

/**
 * The extended model base implementation for the ShoppingOrder service. Represents a row in the &quot;rivetlogic_ecommerce_ShoppingOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingOrderImpl}.
 * </p>
 *
 * @author isaiulate
 * @see ShoppingOrderImpl
 * @see com.rivetlogic.ecommerce.model.ShoppingOrder
 * @generated
 */
public abstract class ShoppingOrderBaseImpl extends ShoppingOrderModelImpl
	implements ShoppingOrder {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Shopping Order model instance should use the {@link ShoppingOrder} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ShoppingOrderLocalServiceUtil.addShoppingOrder(this);
		}
		else {
			ShoppingOrderLocalServiceUtil.updateShoppingOrder(this);
		}
	}
}