/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.ecommerce.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rivetlogic.ecommerce.model.ShoppingOrder;
import com.rivetlogic.ecommerce.model.ShoppingOrderModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ShoppingOrder service. Represents a row in the &quot;rivetlogic_ecommerce_ShoppingOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rivetlogic.ecommerce.model.ShoppingOrderModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingOrderImpl}.
 * </p>
 *
 * @author isaiulate
 * @see ShoppingOrderImpl
 * @see com.rivetlogic.ecommerce.model.ShoppingOrder
 * @see com.rivetlogic.ecommerce.model.ShoppingOrderModel
 * @generated
 */
public class ShoppingOrderModelImpl extends BaseModelImpl<ShoppingOrder>
	implements ShoppingOrderModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Shopping Order model instance should use the {@link com.rivetlogic.ecommerce.model.ShoppingOrder} interface instead.
	 */
	public static final String TABLE_NAME = "rivetlogic_ecommerce_ShoppingOrder";
	public static final Object[][] TABLE_COLUMNS = {
			{ "orderId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "orderStatus", Types.VARCHAR },
			{ "customerEmail", Types.VARCHAR },
			{ "customerName", Types.VARCHAR },
			{ "customerPhone", Types.VARCHAR },
			{ "shippingAddress1", Types.VARCHAR },
			{ "shippingAddress2", Types.VARCHAR },
			{ "shippingCity", Types.VARCHAR },
			{ "shippingPostalCode", Types.VARCHAR },
			{ "shippingStateProvince", Types.VARCHAR },
			{ "shippingCountry", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table rivetlogic_ecommerce_ShoppingOrder (orderId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,orderStatus VARCHAR(75) null,customerEmail VARCHAR(75) null,customerName VARCHAR(75) null,customerPhone VARCHAR(75) null,shippingAddress1 VARCHAR(75) null,shippingAddress2 VARCHAR(75) null,shippingCity VARCHAR(75) null,shippingPostalCode VARCHAR(75) null,shippingStateProvince VARCHAR(75) null,shippingCountry VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table rivetlogic_ecommerce_ShoppingOrder";
	public static final String ORDER_BY_JPQL = " ORDER BY shoppingOrder.orderId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY rivetlogic_ecommerce_ShoppingOrder.orderId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rivetlogic.ecommerce.model.ShoppingOrder"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rivetlogic.ecommerce.model.ShoppingOrder"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rivetlogic.ecommerce.model.ShoppingOrder"),
			true);
	public static long ORDERSTATUS_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long ORDERID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rivetlogic.ecommerce.model.ShoppingOrder"));

	public ShoppingOrderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _orderId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOrderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _orderId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ShoppingOrder.class;
	}

	@Override
	public String getModelClassName() {
		return ShoppingOrder.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("orderId", getOrderId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("orderStatus", getOrderStatus());
		attributes.put("customerEmail", getCustomerEmail());
		attributes.put("customerName", getCustomerName());
		attributes.put("customerPhone", getCustomerPhone());
		attributes.put("shippingAddress1", getShippingAddress1());
		attributes.put("shippingAddress2", getShippingAddress2());
		attributes.put("shippingCity", getShippingCity());
		attributes.put("shippingPostalCode", getShippingPostalCode());
		attributes.put("shippingStateProvince", getShippingStateProvince());
		attributes.put("shippingCountry", getShippingCountry());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long orderId = (Long)attributes.get("orderId");

		if (orderId != null) {
			setOrderId(orderId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String orderStatus = (String)attributes.get("orderStatus");

		if (orderStatus != null) {
			setOrderStatus(orderStatus);
		}

		String customerEmail = (String)attributes.get("customerEmail");

		if (customerEmail != null) {
			setCustomerEmail(customerEmail);
		}

		String customerName = (String)attributes.get("customerName");

		if (customerName != null) {
			setCustomerName(customerName);
		}

		String customerPhone = (String)attributes.get("customerPhone");

		if (customerPhone != null) {
			setCustomerPhone(customerPhone);
		}

		String shippingAddress1 = (String)attributes.get("shippingAddress1");

		if (shippingAddress1 != null) {
			setShippingAddress1(shippingAddress1);
		}

		String shippingAddress2 = (String)attributes.get("shippingAddress2");

		if (shippingAddress2 != null) {
			setShippingAddress2(shippingAddress2);
		}

		String shippingCity = (String)attributes.get("shippingCity");

		if (shippingCity != null) {
			setShippingCity(shippingCity);
		}

		String shippingPostalCode = (String)attributes.get("shippingPostalCode");

		if (shippingPostalCode != null) {
			setShippingPostalCode(shippingPostalCode);
		}

		String shippingStateProvince = (String)attributes.get(
				"shippingStateProvince");

		if (shippingStateProvince != null) {
			setShippingStateProvince(shippingStateProvince);
		}

		String shippingCountry = (String)attributes.get("shippingCountry");

		if (shippingCountry != null) {
			setShippingCountry(shippingCountry);
		}
	}

	@Override
	public long getOrderId() {
		return _orderId;
	}

	@Override
	public void setOrderId(long orderId) {
		_orderId = orderId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getOrderStatus() {
		if (_orderStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _orderStatus;
		}
	}

	@Override
	public void setOrderStatus(String orderStatus) {
		_columnBitmask |= ORDERSTATUS_COLUMN_BITMASK;

		if (_originalOrderStatus == null) {
			_originalOrderStatus = _orderStatus;
		}

		_orderStatus = orderStatus;
	}

	public String getOriginalOrderStatus() {
		return GetterUtil.getString(_originalOrderStatus);
	}

	@Override
	public String getCustomerEmail() {
		if (_customerEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerEmail;
		}
	}

	@Override
	public void setCustomerEmail(String customerEmail) {
		_customerEmail = customerEmail;
	}

	@Override
	public String getCustomerName() {
		if (_customerName == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerName;
		}
	}

	@Override
	public void setCustomerName(String customerName) {
		_customerName = customerName;
	}

	@Override
	public String getCustomerPhone() {
		if (_customerPhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _customerPhone;
		}
	}

	@Override
	public void setCustomerPhone(String customerPhone) {
		_customerPhone = customerPhone;
	}

	@Override
	public String getShippingAddress1() {
		if (_shippingAddress1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _shippingAddress1;
		}
	}

	@Override
	public void setShippingAddress1(String shippingAddress1) {
		_shippingAddress1 = shippingAddress1;
	}

	@Override
	public String getShippingAddress2() {
		if (_shippingAddress2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _shippingAddress2;
		}
	}

	@Override
	public void setShippingAddress2(String shippingAddress2) {
		_shippingAddress2 = shippingAddress2;
	}

	@Override
	public String getShippingCity() {
		if (_shippingCity == null) {
			return StringPool.BLANK;
		}
		else {
			return _shippingCity;
		}
	}

	@Override
	public void setShippingCity(String shippingCity) {
		_shippingCity = shippingCity;
	}

	@Override
	public String getShippingPostalCode() {
		if (_shippingPostalCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _shippingPostalCode;
		}
	}

	@Override
	public void setShippingPostalCode(String shippingPostalCode) {
		_shippingPostalCode = shippingPostalCode;
	}

	@Override
	public String getShippingStateProvince() {
		if (_shippingStateProvince == null) {
			return StringPool.BLANK;
		}
		else {
			return _shippingStateProvince;
		}
	}

	@Override
	public void setShippingStateProvince(String shippingStateProvince) {
		_shippingStateProvince = shippingStateProvince;
	}

	@Override
	public String getShippingCountry() {
		if (_shippingCountry == null) {
			return StringPool.BLANK;
		}
		else {
			return _shippingCountry;
		}
	}

	@Override
	public void setShippingCountry(String shippingCountry) {
		_shippingCountry = shippingCountry;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ShoppingOrder.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ShoppingOrder toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ShoppingOrder)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ShoppingOrderImpl shoppingOrderImpl = new ShoppingOrderImpl();

		shoppingOrderImpl.setOrderId(getOrderId());
		shoppingOrderImpl.setGroupId(getGroupId());
		shoppingOrderImpl.setCompanyId(getCompanyId());
		shoppingOrderImpl.setUserId(getUserId());
		shoppingOrderImpl.setUserName(getUserName());
		shoppingOrderImpl.setCreateDate(getCreateDate());
		shoppingOrderImpl.setModifiedDate(getModifiedDate());
		shoppingOrderImpl.setOrderStatus(getOrderStatus());
		shoppingOrderImpl.setCustomerEmail(getCustomerEmail());
		shoppingOrderImpl.setCustomerName(getCustomerName());
		shoppingOrderImpl.setCustomerPhone(getCustomerPhone());
		shoppingOrderImpl.setShippingAddress1(getShippingAddress1());
		shoppingOrderImpl.setShippingAddress2(getShippingAddress2());
		shoppingOrderImpl.setShippingCity(getShippingCity());
		shoppingOrderImpl.setShippingPostalCode(getShippingPostalCode());
		shoppingOrderImpl.setShippingStateProvince(getShippingStateProvince());
		shoppingOrderImpl.setShippingCountry(getShippingCountry());

		shoppingOrderImpl.resetOriginalValues();

		return shoppingOrderImpl;
	}

	@Override
	public int compareTo(ShoppingOrder shoppingOrder) {
		long primaryKey = shoppingOrder.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ShoppingOrder)) {
			return false;
		}

		ShoppingOrder shoppingOrder = (ShoppingOrder)obj;

		long primaryKey = shoppingOrder.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ShoppingOrderModelImpl shoppingOrderModelImpl = this;

		shoppingOrderModelImpl._originalUserId = shoppingOrderModelImpl._userId;

		shoppingOrderModelImpl._setOriginalUserId = false;

		shoppingOrderModelImpl._originalOrderStatus = shoppingOrderModelImpl._orderStatus;

		shoppingOrderModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ShoppingOrder> toCacheModel() {
		ShoppingOrderCacheModel shoppingOrderCacheModel = new ShoppingOrderCacheModel();

		shoppingOrderCacheModel.orderId = getOrderId();

		shoppingOrderCacheModel.groupId = getGroupId();

		shoppingOrderCacheModel.companyId = getCompanyId();

		shoppingOrderCacheModel.userId = getUserId();

		shoppingOrderCacheModel.userName = getUserName();

		String userName = shoppingOrderCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			shoppingOrderCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			shoppingOrderCacheModel.createDate = createDate.getTime();
		}
		else {
			shoppingOrderCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			shoppingOrderCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			shoppingOrderCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		shoppingOrderCacheModel.orderStatus = getOrderStatus();

		String orderStatus = shoppingOrderCacheModel.orderStatus;

		if ((orderStatus != null) && (orderStatus.length() == 0)) {
			shoppingOrderCacheModel.orderStatus = null;
		}

		shoppingOrderCacheModel.customerEmail = getCustomerEmail();

		String customerEmail = shoppingOrderCacheModel.customerEmail;

		if ((customerEmail != null) && (customerEmail.length() == 0)) {
			shoppingOrderCacheModel.customerEmail = null;
		}

		shoppingOrderCacheModel.customerName = getCustomerName();

		String customerName = shoppingOrderCacheModel.customerName;

		if ((customerName != null) && (customerName.length() == 0)) {
			shoppingOrderCacheModel.customerName = null;
		}

		shoppingOrderCacheModel.customerPhone = getCustomerPhone();

		String customerPhone = shoppingOrderCacheModel.customerPhone;

		if ((customerPhone != null) && (customerPhone.length() == 0)) {
			shoppingOrderCacheModel.customerPhone = null;
		}

		shoppingOrderCacheModel.shippingAddress1 = getShippingAddress1();

		String shippingAddress1 = shoppingOrderCacheModel.shippingAddress1;

		if ((shippingAddress1 != null) && (shippingAddress1.length() == 0)) {
			shoppingOrderCacheModel.shippingAddress1 = null;
		}

		shoppingOrderCacheModel.shippingAddress2 = getShippingAddress2();

		String shippingAddress2 = shoppingOrderCacheModel.shippingAddress2;

		if ((shippingAddress2 != null) && (shippingAddress2.length() == 0)) {
			shoppingOrderCacheModel.shippingAddress2 = null;
		}

		shoppingOrderCacheModel.shippingCity = getShippingCity();

		String shippingCity = shoppingOrderCacheModel.shippingCity;

		if ((shippingCity != null) && (shippingCity.length() == 0)) {
			shoppingOrderCacheModel.shippingCity = null;
		}

		shoppingOrderCacheModel.shippingPostalCode = getShippingPostalCode();

		String shippingPostalCode = shoppingOrderCacheModel.shippingPostalCode;

		if ((shippingPostalCode != null) && (shippingPostalCode.length() == 0)) {
			shoppingOrderCacheModel.shippingPostalCode = null;
		}

		shoppingOrderCacheModel.shippingStateProvince = getShippingStateProvince();

		String shippingStateProvince = shoppingOrderCacheModel.shippingStateProvince;

		if ((shippingStateProvince != null) &&
				(shippingStateProvince.length() == 0)) {
			shoppingOrderCacheModel.shippingStateProvince = null;
		}

		shoppingOrderCacheModel.shippingCountry = getShippingCountry();

		String shippingCountry = shoppingOrderCacheModel.shippingCountry;

		if ((shippingCountry != null) && (shippingCountry.length() == 0)) {
			shoppingOrderCacheModel.shippingCountry = null;
		}

		return shoppingOrderCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{orderId=");
		sb.append(getOrderId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", orderStatus=");
		sb.append(getOrderStatus());
		sb.append(", customerEmail=");
		sb.append(getCustomerEmail());
		sb.append(", customerName=");
		sb.append(getCustomerName());
		sb.append(", customerPhone=");
		sb.append(getCustomerPhone());
		sb.append(", shippingAddress1=");
		sb.append(getShippingAddress1());
		sb.append(", shippingAddress2=");
		sb.append(getShippingAddress2());
		sb.append(", shippingCity=");
		sb.append(getShippingCity());
		sb.append(", shippingPostalCode=");
		sb.append(getShippingPostalCode());
		sb.append(", shippingStateProvince=");
		sb.append(getShippingStateProvince());
		sb.append(", shippingCountry=");
		sb.append(getShippingCountry());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append("com.rivetlogic.ecommerce.model.ShoppingOrder");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>orderId</column-name><column-value><![CDATA[");
		sb.append(getOrderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderStatus</column-name><column-value><![CDATA[");
		sb.append(getOrderStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerEmail</column-name><column-value><![CDATA[");
		sb.append(getCustomerEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerName</column-name><column-value><![CDATA[");
		sb.append(getCustomerName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customerPhone</column-name><column-value><![CDATA[");
		sb.append(getCustomerPhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingAddress1</column-name><column-value><![CDATA[");
		sb.append(getShippingAddress1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingAddress2</column-name><column-value><![CDATA[");
		sb.append(getShippingAddress2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingCity</column-name><column-value><![CDATA[");
		sb.append(getShippingCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingPostalCode</column-name><column-value><![CDATA[");
		sb.append(getShippingPostalCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingStateProvince</column-name><column-value><![CDATA[");
		sb.append(getShippingStateProvince());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shippingCountry</column-name><column-value><![CDATA[");
		sb.append(getShippingCountry());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ShoppingOrder.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ShoppingOrder.class
		};
	private long _orderId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _orderStatus;
	private String _originalOrderStatus;
	private String _customerEmail;
	private String _customerName;
	private String _customerPhone;
	private String _shippingAddress1;
	private String _shippingAddress2;
	private String _shippingCity;
	private String _shippingPostalCode;
	private String _shippingStateProvince;
	private String _shippingCountry;
	private long _columnBitmask;
	private ShoppingOrder _escapedModel;
}